#ifndef FW_VERSION_H
#define FW_VERSION_H

#define FW_VERSION_MAJOR 1U
#define FW_VERSION_MINOR 3U
#define FW_VERSION_PATCH 0U

#define FW_VERSION_U32 ((FW_VERSION_MAJOR << 16U) | (FW_VERSION_MINOR << 8U) | (FW_VERSION_PATCH))

#define CFG_STRUCT_VERSION 3U

#endif /* FW_VERSION_H */
